### ISSUE TITLE
Do you have any progress now？

### ISSUE THREAD

**Issue by zakiso** [khallmark/ds4mac#1]
Friend, where have you been? We need you, do you have any progress now?

**Comment by chienkuo** [comment]
it would be a nick work if it has been done.

**Comment by henrysipp** [comment]
+1

**Comment by arikon** [comment]
@khallmark Hello! Did you have time to gain some progress on this great work?

**Comment by khallmark** [comment]
Time to come back to this, I think.

**Comment by y5r43l** [comment]
@khallmark Hello from Brazil! I know absolutely about ObjC/C++ programming but I do know a little about Java and I'm willing to learn ObjC/C++ if I could help you to finish this project. Just tell me if theres something I can do to help.

**Comment by matthewbauer** [comment]
There is now a driver in Steam for DS4 on OS X. It only works while Steam is running though.

**Comment by schroef** [comment]
How is this project coming?

**Comment by nobodywasishere** [comment]
What about now?

**Comment by schroef** [comment]
Seems like a dead project from the programmer

**Comment by nobodywasishere** [comment]
Hm. Would anyone be interested in forking this project to keep working on it? While I know only a little bit about where to go from here, I really want this project to be a thing.

**Comment by schroef** [comment]
Well i got feeling basic movement doesnt work. Im noteven sure osx can support same Bluetooth channels or whatever they are called.

For a while im using Joystick mapper, its not the perfect feeling but it works.

**Comment by nobodywasishere** [comment]
I actually downloaded the project to see if I could try my hand at it and all the IOKit stuff was completely switched around from macOS 10.10 to 10.11, meaning this code would have to be completely redone. 
I’ve been using Joystick Mapper too, and its the best mapper I’ve found actually for what I use it for.
